version: "3.1"
services:
  server:
    image: photo-assassin
    ports:
      - "80:8000"
      - "443:4330"
    volumes:
      - /etc/letsencrypt/live/photo-assassin.prangten.com/privkey.pem:/home/node/app/secret/privkey.pem
      - /etc/letsencrypt/live/photo-assassin.prangten.com/cert.pem:/home/node/app/secret/cert.pem
      - /etc/letsencrypt/live/photo-assassin.prangten.com/chain.pem:/home/node/app/secret/chain.pem
      - ./games:/home/node/app/games
    env_file: .env
    restart: on-failure
